Repository pomerium/ingress-controller, pull requests merged in 2021-12, with the labels that each got.

#97 set ImplementationSpecific path behavior to Prefix
  pomerium/ingress_to_route.go
Labels: improvement

#104 more robust yaml/json parsing in annotations
  go.sum
  pomerium/ingress_annotations.go
  pomerium/ingress_annotations_test.go
Labels: bug

#110 bump pomerium core
  cmd/grpc.go
  cmd/serve.go
  go.mod
  go.sum
  pomerium/validate.go
Labels: dependencies
