Repository pomerium/ingress-controller, pull requests merged in 2022-05, with the labels that each got.

#191 upgrade pomerium 0.17.2
  go.mod
  go.sum
  pomerium/validate.go
Labels: dependencies

#196 tcp tunnel support
  model/ingress_config.go
  pomerium/ingress_annotations.go
  pomerium/ingress_to_route.go
  pomerium/routes_test.go
Labels: enhancement, docs

#183 Support path-related rewrite annotations
  pomerium/ingress_annotations.go
  pomerium/ingress_annotations_test.go
Labels: enhancement, docs

#198 support secrets for set request/response headers and k8s access token
  controllers/fetch.go
  go.mod
  go.sum
  model/ingress_config.go
  pomerium/ingress_annotations.go
  pomerium/ingress_annotations_test.go
Labels: enhancement, docs

#208 fix custom secrets
  controllers/controller_integration_test.go
  model/ingress_config.go
  pomerium/ingress_annotations.go
  pomerium/ingress_annotations_test.go
  pomerium/routes_test.go
Labels: bug

#215 add k8s token test, bump to 0-17 tip
  go.mod
  go.sum
  pomerium/routes_test.go
Labels: bug

#216 bump go 1.18
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  Dockerfile
  go.mod
  go.sum
Labels: dependencies

#218 add settings CRD and basic status
  Makefile
  PROJECT
  apis/ingress/v1/groupversion_info.go
  apis/ingress/v1/settings_types.go
  apis/ingress/v1/zz_generated.deepcopy.go
  cmd/serve.go
  config/crd/bases/ingress.pomerium.io_settings.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_ingress_settings.yaml
  config/crd/patches/webhook_in_ingress_settings.yaml
  config/rbac/ingress_settings_editor_role.yaml
  config/rbac/ingress_settings_viewer_role.yaml
  config/samples/ingress_v1_settings.yaml
  controllers/builder.go
  controllers/controller.go
  controllers/controller_integration_test.go
  controllers/deps.go
  controllers/fetch.go
  controllers/ingress_class.go
  controllers/reconcile.go
  controllers/reporter.go
  controllers/reporter/ingress.go
  go.mod
  go.sum
  model/ingress_config.go
  model/registry.go
  pomerium/certs.go
  pomerium/envoy/envoy.go
  pomerium/envoy/envoy_darwin_amd64.go
  pomerium/envoy/envoy_darwin_arm64.go
  pomerium/envoy/envoy_linux_amd64.go
  pomerium/envoy/envoy_linux_arm64.go
  pomerium/routes.go
  pomerium/routes_test.go
  pomerium/sync.go
  util/namespaced_name.go
  util/namespaced_name_test.go
Labels: enhancement
