Repository pomerium/ingress-controller, pull requests merged in 2022-01, with the labels that each got.

#112 routes: bypass service dns name and use endpoints directly
  controllers/controller.go
  controllers/controller_integration_test.go
  controllers/fetch.go
  model/ingress_config.go
  pomerium/ingress_to_route.go
  pomerium/routes_test.go
Labels: improvement

#116 deployment: support multi-arch images for `main` tag
  .github/workflows/docker-main.yaml
  Dockerfile
Labels: deployment

#119 add service_upstream annotation to enable use of service proxy and not endpoints directly
  go.sum
  model/ingress_config.go
  pomerium/ingress_annotations.go
  pomerium/ingress_to_route.go
  pomerium/routes_test.go
Labels: improvement

#118 bump envoy to 1.20.1
  scripts/get-envoy.bash
Labels: dependencies

#120 deployment: fix multi-arch rolling image
  Dockerfile
  Dockerfile.release
  goreleaser.yaml
Labels: bug

#121 fix lint complaints
  README.md
  cmd/serve.go
  controllers/builder.go
  controllers/controller.go
  controllers/controller_integration_test.go
  controllers/fetch.go
  controllers/once.go
  controllers/once_test.go
  main.go
  model/ingress_config.go
  pomerium/envoy/embed.go
  pomerium/envoy/envoy_darwin_arm64.go
  pomerium/ingress_annotations.go
  pomerium/ingress_annotations_test.go
  pomerium/sync.go
Labels: improvement

#122 add load balancing configs
  pomerium/ingress_annotations.go
  pomerium/ingress_annotations_test.go
Labels: improvement

#130 bump core to v0.16.2
  go.mod
  go.sum
Labels: dependencies

#127 deployment: enable goreleaser buildx
  goreleaser.yaml
Labels: bug, deployment
