Repository pomerium/ingress-controller, pull requests merged in 2022-02, with the labels that each got.

#137 Fix typo
  README.md
Labels: docs

#145 config: sort routes
  .golangci.yml
  controllers/builder.go
  pomerium/route_list.go
  pomerium/routes.go
  pomerium/routes_test.go
Labels: bug

#150 do not expect Endpoints for ExternalName Service type
  controllers/fetch.go
  go.sum
Labels: bug

#151 support default certificate
  Makefile
  controllers/builder.go
  controllers/client_mock.go
  controllers/controller.go
  controllers/controller_integration_test.go
  controllers/controller_test.go
  controllers/deps.go
  controllers/fetch.go
  controllers/ingress_class.go
  controllers/reconcile.go
  go.mod
  model/ingress_config.go
Labels: enhancement, docs
