Repository pomerium/ingress-controller, pull requests merged in 2022-09, with the labels that each got.

#358 pomerium/ctrl: use a file manager for certificates to delete orphaned files
  internal/filemgr/filemgr.go
  internal/filemgr/filemgr_test.go
  pomerium/ctrl/bootstrap.go
  pomerium/ctrl/bootstrap_test.go
  pomerium/ctrl/run.go
Labels: improvement

#345 envoy: upgrade to 1.23.1
  cmd/all_in_one.go
  go.mod
  go.sum
  scripts/get-envoy.bash
Labels: blocked

#361 fix expected k8s service account secret type
  apis/ingress/v1/pomerium_types.go
  config/crd/bases/ingress.pomerium.io_pomerium.yaml
  deployment.yaml
  pomerium/ingress_annotations.go
  pomerium/ingress_annotations_test.go
  pomerium/routes_test.go
Labels: improvement

#369 bump to v19.0 docker image
  config/pomerium/deployment/image.yaml
  deployment.yaml
Labels: dependencies

#376 Bump sigs.k8s.io/controller-runtime from 0.12.3 to 0.13.0
  controllers/deps/registry_client.go
  controllers/mock/client.go
  controllers/mock/mock.go
  controllers/settings/fetch_test.go
  go.mod
  go.sum
  main.go
Labels: dependencies
