Repository pomerium/ingress-controller, pull requests merged in 2023-07, with the labels that each got.

#694 add useProxyProtocol option to the CRD
  apis/ingress/v1/pomerium_types.go
  apis/ingress/v1/zz_generated.deepcopy.go
  config/crd/bases/ingress.pomerium.io_pomerium.yaml
  deployment.yaml
  pomerium/config.go
Labels: docs

#702 dependencies: upgrade core
  go.mod
  go.sum
  pomerium/validate.go
Labels: dependencies

#701 settings: add access_log_fields and authorize_log_fields
  apis/ingress/v1/pomerium_types.go
  apis/ingress/v1/zz_generated.deepcopy.go
  config/crd/bases/ingress.pomerium.io_pomerium.yaml
  deployment.yaml
  pomerium/config.go
Labels: enhancement
