Repository pomerium/ingress-controller, pull requests merged in 2023-12, with the labels that each got.

#835 ingress-controller/config: remove redis
  apis/ingress/v1/deprecation.go
  apis/ingress/v1/deprecation_test.go
  apis/ingress/v1/pomerium_types.go
  apis/ingress/v1/zz_generated.deepcopy.go
  config/crd/bases/ingress.pomerium.io_pomerium.yaml
  controllers/settings/fetch.go
  controllers/settings/fetch_test.go
  deployment.yaml
  pomerium/config.go
  pomerium/ctrl/bootstrap.go
  reference.md
Labels: debt

#836 ingress-controller/ci: upgrade golangci-lint
  .github/workflows/lint.yml
  Makefile
  go.mod
  go.sum
  tools.go
  util/restart_test.go
Labels: ci

#837 docs: update pass identity headers reference link
  apis/ingress/v1/pomerium_types.go
  config/crd/bases/ingress.pomerium.io_pomerium.yaml
  deployment.yaml
Labels: docs

#840 ci: use standard runners
  .github/workflows/backport.yaml
  .github/workflows/docker-main.yaml
  .github/workflows/docker-version-branches.yaml
  .github/workflows/docs.yaml
  .github/workflows/test.yaml
Labels: ci
