Repository pomerium/ingress-controller, pull requests merged in 2023-01, with the labels that each got.

#484 add cspell pre-commit hook
  .pre-commit-config.yaml
  Makefile
  apis/ingress/v1/pomerium_types.go
  controllers/ingress/controller.go
  controllers/settings/controller.go
  controllers/settings/fetch_test.go
  cspell.config.yaml
  go.mod
  internal/init.go
  model/registry.go
  pomerium/ingress_to_route.go
  util/namespaced_name_test.go
Labels: ci

#485 config: add certificate authorities
  apis/ingress/v1/pomerium_types.go
  apis/ingress/v1/zz_generated.deepcopy.go
  config/crd/bases/ingress.pomerium.io_pomerium.yaml
  controllers/settings/fetch.go
  deployment.yaml
  model/ingress_config.go
  pomerium/config.go
  pomerium/ctrl/run.go
Labels: enhancement

#493 bump core to v0.21.0-rc1
  go.mod
  go.sum
Labels: dependencies

#501 bump core to v0.21.0-rc2
  go.mod
  go.sum
Labels: dependencies, backport 0-21-0

#502 push release branches to the dockerhub
  .github/workflows/docker-version-branches.yaml
Labels: ci, backport 0-21-0
