Repository pomerium/ingress-controller, pull requests merged in 2023-11, with the labels that each got.

#806 make: update docker-build target
  .github/workflows/test.yaml
  Dockerfile
  Dockerfile.ci
  Makefile
Labels: ci

#807 ci: replace action-pull-request-another-repo
  .github/workflows/docs.yaml
  scripts/open-docs-pull-request.sh
Labels: ci

#811 ingress-controller/config: add pass_identity_headers option
  apis/ingress/v1/pomerium_types.go
  apis/ingress/v1/zz_generated.deepcopy.go
  config/crd/bases/ingress.pomerium.io_pomerium.yaml
  deployment.yaml
  go.mod
  go.sum
  pomerium/config.go
  pomerium/ingress_annotations_test.go
Labels: improvement

#814 ci: add release.yaml, rm changelog.sh
  .github/release.yaml
  scripts/changelog.sh
Labels: ci, backport 0-24-0

#816 set core to v0.24.0
  go.mod
  go.sum
Labels: ignore-changelog
