Repository pomerium/ingress-controller, pull requests merged in 2024-01, with the labels that each got.

#858 ci: publish versioned docker images
  .github/workflows/release.yaml
Labels: ci

#861 ci: add setup-go action to build-docker job
  .github/workflows/test.yaml
Labels: ci

#860 bump core to latest
  go.mod
  go.sum
Labels: dependencies, ignore-changelog

#865 set core to v0.25
  go.mod
  go.sum
Labels: dependencies, ignore-changelog

#864 upgrade deprecated kustomization rules
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/gen_secrets/kustomization.yaml
  config/pomerium/deployment/kustomization.yaml
  config/pomerium/kustomization.yaml
  config/pomerium/rbac/kustomization.yaml
  config/pomerium/service/kustomization.yaml
  config/prometheus/coreos-podmonitor.yaml
  config/prometheus/gke-podmonitor.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
Labels: debt

#866 set docker image target to v0.25.0
  config/pomerium/deployment/image.yaml
  deployment.yaml
Labels: ci, ignore-changelog

#867 ci: fix docker image version tag check
  .github/workflows/release.yaml
Labels: ci, ignore-changelog, backport 0-25-0

#869 ci: check image tag
  .github/workflows/release.yaml
  scripts/check-image-tag.sh
Labels: ci, ignore-changelog, backport 0-25-0

#872 ingress-controller/settings: remove cookie secure option
  apis/ingress/v1/pomerium_types.go
  apis/ingress/v1/zz_generated.deepcopy.go
  config/crd/bases/ingress.pomerium.io_pomerium.yaml
  deployment.yaml
  pomerium/config.go
  reference.md
Labels: breaking, debt

#877 ingress-controller/config: fix disabled set response headers
  pomerium/ingress_annotations.go
  pomerium/ingress_annotations_test.go
Labels: bug, backport 0-25-0

#880 update core to latest main
  go.mod
  go.sum
Labels: dependencies, ignore-changelog
