Repository pomerium/ingress-controller, pull requests merged in 2024-05, with the labels that each got.

#945 Support for empty host in ingress rules (#941)
  go.mod
  model/ingress_config.go
  pomerium/ingress_annotations.go
  pomerium/ingress_to_route.go
  pomerium/routes_test.go
Labels: enhancement

#953 Upgrade controller-runtime to v0.15.0 and k8s api to v0.30.0
  controllers/ingress/controller.go
  controllers/ingress/controller_integration_test.go
  controllers/ingress/deps.go
  controllers/settings/controller.go
  go.mod
  go.sum
  util/generic/builder.go
  util/generic/doc.go
  util/generic/gvk.go
Labels: dependencies

#954 ci: update core to latest
  go.mod
  go.sum
Labels: ci

#957 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#958 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#959 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#960 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#961 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#962 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci
