Repository pomerium/ingress-controller, pull requests merged in 2025-03, with the labels that each got.

#1109 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#1120 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#1129 revert 1030
  config/pomerium/service/proxy.yaml
  deployment.yaml
Labels: backport 0-29-0

#1132 upgrade main
  go.mod
  go.sum
Labels: bug

#1131 ci: build docker images for experimental/* branches
  .github/workflows/docker-version-branches.yaml
Labels: ci

#1133 upgrade main
  go.mod
  go.sum
Labels: bug
