Repository pomerium/ingress-controller, pull requests merged in 2025-04, with the labels that each got.

#1143 upgrade to go v1.24
  .github/workflows/docker-main.yaml
  .github/workflows/docker-version-branches.yaml
  .github/workflows/docs.yaml
  .github/workflows/lint.yml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .github/workflows/update-core.yaml
  .tool-versions
  Makefile
  go.mod
  go.sum
  pomerium/gateway/backendrefs.go
  pomerium/gateway/filters.go
  tools.go
Labels: debt

#1121 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#1146 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#1150 add support for the route 'depends_on' option
  go.mod
  go.sum
  pomerium/ingress_annotations.go
  pomerium/ingress_annotations_test.go
Labels: enhancement

#1149 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci
