Repository pomerium/ingress-controller, pull requests merged in 2025-08, with the labels that each got.

#1203 feat(ingress) : add common_lb_config as an ingress config annotation
  go.mod
  pomerium/ingress_annotations.go
  pomerium/ingress_annotations_test.go
  pomerium/proto.go
Labels: Improvement

#1186 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#1205 controller: skip name check
  cmd/all_in_one.go
  cmd/controller.go
  go.mod
Labels: bug, backport 0-30-0

#1204 setup-envtest: use latest patch version available
  .github/workflows/test.yaml
  Makefile
Labels: dependencies, backport 0-30-0

#1208 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#1214 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci
