Repository pomerium/ingress-controller, pull requests merged in 2025-01, with the labels that each got.

#1085 settings: add codec_type
  apis/ingress/v1/pomerium_types.go
  apis/ingress/v1/zz_generated.deepcopy.go
  cmd/all_in_one.go
  config/crd/bases/ingress.pomerium.io_pomerium.yaml
  config/pomerium/deployment/no-root.yaml
  config/pomerium/deployment/ports.yaml
  config/pomerium/service/proxy.yaml
  deployment.yaml
  go.mod
  go.sum
  pomerium/config.go
Labels: enhancement

#1081 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#1086 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci

#1088 Makefile: unset GOOS for get-envoy command
  Makefile
Labels: ignore-changelog

#1090 ci: update core to latest commit in main
  go.mod
  go.sum
Labels: ci
